### ISSUE TITLE
Camera field of view calculation

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-documentation#15]
See the definition of camera field of view in the CTA Glossary

**Comment by orelgueta** [comment]
I have code that does it already, will make an application out of it. In addition, Konrad has an application as well within sim_telarray (called fov.cc), we might want to use that as well?

**Comment by GernotMaier** [comment]
Not exactly sure I understand: you want to use both your code and Konrad's for the same purpose?

This is a bit of a 'borderline' workflow: I guess we only need that for the TDRs, but otherwise now.

**Comment by orelgueta** [comment]
> Not exactly sure I understand: you want to use both your code and Konrad's for the same purpose?

Not really, was just mentioning so that you are aware that Konrad also has a tool for this. My preference is to use my tool, but that is just cause I know it.

> This is a bit of a 'borderline' workflow: I guess we only need that for the TDRs, but otherwise now.

Not sure I understand this sentence, is it cut?

**Comment by GernotMaier** [comment]
Last sentence should be:

This is a bit of a 'borderline' workflow: I guess we only need that for the TDRs, but otherwise **not**

**Comment by orelgueta** [comment]
True, except we always print the FOV on every plot of the camera. We don't need to continue doing that though. Anyway, since the values of Konrad's application and mine agree, I will choose to use mine for now. If something changes, we switch.

**Comment by GernotMaier** [comment]
Agreed

**Comment by orelgueta** [comment]
What did you have in mind for this exactly? An application that returns the FOV of a telescope given its name? An application which plots the camera with the FOV printed on the figure? An application that returns the FOV given a list of pixel positions and a focal length?
All of these already exist, just wondering which should actually be made "official".

**Comment by GernotMaier** [comment]
I think this is a workflow which is only needed for requirements checking, but not later when the FOV changes. 

So yes, this should be the 'official' one:

 An application that returns the FOV of a telescope given its name, using the list of pixel positions and focal length.

But it would also be nice to plot it on top of the camera.

**Comment by orelgueta** [comment]
Reviewed and approved, can @GernotMaier please take a look and make sure it does what you intended so we can close the issue?

**Comment by GernotMaier** [comment]
@orelgueta : Where should I look?

**Comment by orelgueta** [comment]
This is the application:

https://github.com/gammasim/gammasim-tools/blob/master/applications/validate_camera_fov.py

The definition of an application is not clear yet, so in this case the user chooses the telescope within the python code, but I guess this meets our needs for now (and probably ever).

**Comment by GernotMaier** [comment]
` python ./validate_camera_fov.py --h
Traceback (most recent call last):
  File "./validate_camera_fov.py", line 8, in <module>
    from simtools.model.camera import Camera
  File "/Users/maierg/Experiments/gammasim/gammasim-tools/simtools/model/camera.py", line 7, in <module>
    import scipy.spatial.cKDTree as KDTree
ModuleNotFoundError: No module named 'scipy'`

Missing package for environment?

**Comment by orelgueta** [comment]
Yes, sorry, I honestly did not use the environment so far (long story than involved me re-installing my entire Conda).
@RaulRPrado, may I ask you to please add scipy to the environment? I don't want to break anything if I do it myself in my branch.

**Comment by RaulRPrado** [comment]
Done. I also fixed a bug that I added on the cKDTree import.
Do we need this namespace:
import cKDTree as KDTree
?

**Comment by RaulRPrado** [comment]
@GernotMaier, there is no -h option in validate_camera_fov.py. The argparse stuff is not implemented yet. Just run it without options and have a look at the code, which is very short. In principle, these parameters will be catch by argparse:
site = 'south'
telescope = 'lst'
version = 'prod4'
label = 'lst-test'

**Comment by orelgueta** [comment]
> Do we need this namespace:
> import cKDTree as KDTree
> ?

I would say it's a bit nicer to use KDTree instead of cKDTree no? I don't mind removing it though if you feel strongly about it.

**Comment by orelgueta** [comment]
> @GernotMaier, there is no -h option in validate_camera_fov.py. The argparse stuff is not implemented yet.

Yes, this is what I meant with:

> The definition of an application is not clear yet, so in this case the user chooses the telescope within the python code, but I guess this meets our needs for now (and probably ever).

I don't see this application ever used by a "user", so it's fairly useless to implement argparse, but we can of course.

**Comment by GernotMaier** [comment]
OK - so what should I do to test it? Look at the code?

Running it without arguments also doesn't work.

`python ./validate_camera_fov.py

Validating the camera FoV of LST

Traceback (most recent call last):
  File "./validate_camera_fov.py", line 27, in <module>
    telModel = TelescopeModel(
  File "/Users/maierg/Experiments/gammasim/gammasim-tools/simtools/model/telescope_model.py", line 96, in __init__
    self._modelFilesLocations = cfg.collectConfigArg('modelFilesLocations', modelFilesLocations)
  File "/Users/maierg/Experiments/gammasim/gammasim-tools/simtools/config.py", line 97, in collectConfigArg
    return Path(value) if value is not None else get(name)
  File "/Users/maierg/Experiments/gammasim/gammasim-tools/simtools/config.py", line 69, in get
    config = loadConfig()
  File "/Users/maierg/Experiments/gammasim/gammasim-tools/simtools/config.py", line 51, in loadConfig
    with open(thisFileName, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yml'`

**Comment by orelgueta** [comment]
All applications should be run from the root directory, i.e., gammasim/gammasim-tools, not from the applications directory.
@RaulRPrado, is there a way we can make it work if running from within the applications directory as well?

**Comment by RaulRPrado** [comment]
Yes, of course.

First, you have to either run it from the previous directory (python applications/validate_....py) or set a different config file name. I suggest the first.

Second, in config.yml you have to add the path to the model files. The default ones contains mine and Orel's only. These files are all on svn by now.

Now I see that this kind of "test" or "approval" should be more efficient as a talk, while browsing the code than this.

**Comment by RaulRPrado** [comment]
> All applications should be run from the root directory, i.e., gammasim/gammasim-tools, not from the applications directory.
> @RaulRPrado, is there a way we can make it work if running from within the applications directory as well?

Yes.

**Comment by RaulRPrado** [comment]
> > @GernotMaier, there is no -h option in validate_camera_fov.py. The argparse stuff is not implemented yet.
> 
> Yes, this is what I meant with:
> 
> > The definition of an application is not clear yet, so in this case the user chooses the telescope within the python code, but I guess this meets our needs for now (and probably ever).
> 
> I don't see this application ever used by a "user", so it's fairly useless to implement argparse, but we can of course.

For me, an application is basically a Tool, or a command line executable. We can even consider to turn them into binaries in the future, as ctapipe will do.
But we should discuss this at some point.

**Comment by GernotMaier** [comment]
But some standard behaviour could be implemented. Shouldn't get error messages when running the tools with '-h' or without any arguments.

**Comment by orelgueta** [comment]
> Yes, of course.
> 
> First, you have to either run it from the previous directory (python applications/validate_....py) or set a different config file name. I suggest the first.
> 
> Second, in config.yml you have to add the path to the model files. The default ones contains mine and Orel's only. These files are all on svn by now.
> 
> Now I see that this kind of "test" or "approval" should be more efficient as a talk, while browsing the code than this.

Agreed! Sorry I simply asked you to review it without explaining any of these things, I should have...

> For me, an application is basically a Tool, or a command line executable. We can even consider to turn them into binaries in the future, as ctapipe will do.

I agree this should be the case for many applications, but some of them are so "internal" that I am not sure if it's worth the bother. 
However, if people are used to at least run with -h, we can do it.

**Comment by orelgueta** [comment]
> But some standard behaviour could be implemented. Shouldn't get error messages when running the tools with '-h' or without any arguments.

OK, I will implement argparse with a help option now, but I guess it doesn't stop the reviewing process of the code and it's functionality.

**Comment by orelgueta** [comment]
OK, now there's also a help function and it asks for a telescope to plot/calculate the FoV for.

**Comment by GernotMaier** [comment]
Ok - tested it and kind of works as expected:

- the only thing not drawn is the camera FOV
- the tool does much more than getting the camera FOV

But all of this is ok, we will understand how this will be part of a workflow.

Worried about division by zero?
https://github.com/gammasim/gammasim-tools/blob/e5105c0b31b8365647252c44642a7783ac203cb5/simtools/model/camera.py#L257

Same thing here, I guess you handle this differently?
https://github.com/gammasim/gammasim-tools/blob/e5105c0b31b8365647252c44642a7783ac203cb5/simtools/model/camera.py#L259

Is it clear if this is the focal length or the apparent focal length?
https://github.com/gammasim/gammasim-tools/blob/e5105c0b31b8365647252c44642a7783ac203cb5/simtools/model/camera.py#L41

**Comment by orelgueta** [comment]
> * the only thing not drawn is the camera FOV

The edge pixels are essentially the FoV. I can plot also a circle around (which Konrad does), but I never saw the point of it.

> * the tool does much more than getting the camera FOV

Yes, it also plots as a bonus, following your request actually.

> Worried about division by zero?
> https://github.com/gammasim/gammasim-tools/blob/e5105c0b31b8365647252c44642a7783ac203cb5/simtools/model/camera.py#L257

No, as this is an internal function that doesn't depend much on user input, there is no need to explicitly check for dividing by zero here.

> Same thing here, I guess you handle this differently?
> https://github.com/gammasim/gammasim-tools/blob/e5105c0b31b8365647252c44642a7783ac203cb5/simtools/model/camera.py#L259

This actually should be checked for. Not here though, but at the input to the camera module. There is a layer of protection already, since the focal length is taken from the database, not from the user, but still.
 
> Is it clear if this is the focal length or the apparent focal length?
> https://github.com/gammasim/gammasim-tools/blob/e5105c0b31b8365647252c44642a7783ac203cb5/simtools/model/camera.py#L41

You mean effective focal length? In the line you refer to, no, because it doesn't have to be. However, in the init method it is stated that the effective focal length is preferred. I will add the same parentheses here, just in case.

**Comment by orelgueta** [comment]
OK, so can we close this issue es well?

**Comment by GernotMaier** [comment]
Fine with me.
